# Generated by Django 6.1 on 2026-09-01 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(blank=True, max_length=2000, validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
    ]
